# https://www.techrepublic.com/article/how-to-enable-tcp-bbr-to-improve-network-speed-on-linux/
# enable TCP BBR algorithm for faster network speeds
#net.core.default_qdisc=fq
#net.ipv4.tcp_congestion_control=bbr
# Ping from inside Docker
net.ipv4.ping_group_range = 0 2147483647
# Expose privileged ports
#net.ipv4.ip_unprivileged_port_start=0
# Number of inotify watches https://jellyfin.org/docs/general/administration/troubleshooting/#real-time-monitoring
# https://askubuntu.com/questions/154255/how-can-i-tell-if-i-am-out-of-inotify-watches
# check kernel memory --> slabtop -s c
fs.inotify.max_user_watches=131072
# # Avoid swapping too much, prioritize RAM (default 60)
# vm.swappiness=10
