# https://docs.fedoraproject.org/en-US/fedora-coreos/sysconfig-configure-swaponzram/
# This config file enables a /dev/zram0 device with the default settings

# https://github.com/systemd/zram-generator/blob/main/zram-generator.conf.example
[zram0]
# Sets zRAM to half of physical RAM, maxed at 8GB
zram-size = min(ram / 2, 8192)
# Use zstd for compression, lz4 for speed, lzo-rle for middle-ground
compression-algorithm = lz4
# High priority so it is used before any physical swap
swap-priority = 100
# Use the mount point for memory accounting
fs-type = swap
